// Generated by CoffeeScript 1.4.0
(function() {
  var checkLogin, doLogin, endpoint, fs, getRL, program, readline, request, writeLoginInfo;

  program = require('commander');

  fs = require('fs');

  request = require('request');

  endpoint = require(__dirname + '/endpoint');

  readline = require('readline');

  getRL = function() {
    return readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
  };

  program.version(JSON.parse(fs.readFileSync(__dirname + "/../package.json")).version).parse(process.argv);

  doLogin = function(cb) {
    var rl;
    rl = getRL();
    return rl.question('What is your tempus email? ', function(email) {
      return rl.question('What is your password? ', function(password) {
        return request.post({
          url: endpoint + "/users/authorize",
          headers: {
            Accept: 'application/json'
          },
          json: true,
          body: {
            email: email,
            password: password,
            client: 'tempus-cli'
          }
        }, function(err, res, body) {
          if (err) {
            console.error(err);
            return rl.close();
          } else {
            console.log(res);
            switch (res.statusCode) {
              case 200:
                console.log(200);
                writeLoginInfo(body, cb);
                return rl.close();
              default:
                console.log('An error has occured. Please check your login info');
                return doLogin(cb);
            }
          }
        });
      });
    });
  };

  checkLogin = function(cb) {
    return fs.readFile(process.env.HOME + '/.tempusrc', function(error, data) {
      if (error) {
        return doLogin(cb);
      } else {
        return cb(JSON.parse(data));
      }
    });
  };

  checkLogin(function(user) {
    return console.log(user);
  });

  writeLoginInfo = function(info, cb) {
    var info_text;
    info_text = JSON.stringify(info);
    return fs.writeFile(process.env.HOME + '/.tempusrc', info_text, function(err) {
      if (err) {
        throw err;
      }
      return cb(info);
    });
  };

}).call(this);
